### ISSUE TITLE
Change allowed function to check item name in, not not in

### ISSUE THREAD

**Issue by FuzzyGamesOn** [dontjoome/RE3R_AP_World#3]
https://github.com/dontjoome/RE3R_AP_World/blob/main/residentevil3remake/__init__.py#L29

Basically need to take out the `not` in `item.name not in location_data['allow_item']` on the linked line. Close and ignore issue if you already did the thing. :smiley:

**Comment by TheRealSolidusSnake** [comment]
It's fixed for next time locally, just haven't updated repo since I've been out of the house quite a bit XD appreciate you two looking at that.
